
Vagrant.configure("2") do |config|

	config.vm.define "web" do |web|
		web.vm.box = "ubuntu/xenial64"
		web.vm.provider "virtualbox" do |vb|
	  		config.vm.network "private_network",ip:'192.168.56.6',:adapter => 2
	  		config.vm.hostname = 'web.ci'
	  		vb.name = "web"
				vb.memory='2048'
		end
		#web.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		web.vm.provision "shell", path: "provision.sh"
		web.vm.provision "shell", path: "ansible.sh"
	end

	config.vm.define "Swarm-Manager" do |smanager|
		smanager.vm.box = "ubuntu/xenial64"
		smanager.vm.provider "virtualbox" do |vb|
	  		smanager.vm.network "private_network",ip:'192.168.56.7',:adapter => 2
	  		smanager.vm.hostname = 'swarm.manager'
	  		vb.name = "swarm-manager"
				vb.memory='2048'

		end
		#smanager.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		smanager.vm.provision "shell", path: "provision.sh"
	end

	config.vm.define "Worker1" do |worker|
		worker.vm.box = "ubuntu/xenial64"
		worker.vm.provider "virtualbox" do |vb|
	  		config.vm.network "private_network",ip:'192.168.56.8',:adapter => 2
	  		config.vm.hostname = 'swarm.manager1'
	  		vb.name = "swarm-worker1"
				vb.memory='2048'

		end
		#worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		worker.vm.provision "shell", path: "provision.sh"
	end

	config.vm.define "Worker2" do |worker|
		worker.vm.box = "ubuntu/xenial64"
		worker.vm.provider "virtualbox" do |vb|
	  		config.vm.network "private_network",ip:'192.168.56.9',:adapter => 2
	  		config.vm.hostname = 'swarm.worker2'
	  		vb.name = "swarm-worker2"
				vb.memory='2048'

		end
		#worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		worker.vm.provision "shell", path: "provision.sh"
	end

	config.push.define "atlas" do |push|
	  push.app = "abhijeetka/jenkins"
	  push.token = '4243wZsoj33Omw.atlasv1.8CqDvr2j0y6KSOr3ytVS78RL6xbYsekppf1t4oRUu2kNzG9cXkaIUtaRKMZcXlDegC4'
	end

end
