
Vagrant.configure("2") do |config|

	config.vm.define "Ansible-Master" do |web|
		web.vm.box = "ubuntu/xenial64"
		web.vm.provider "virtualbox" do |vb|
	  		config.vm.network "private_network",ip:'192.168.56.6',:adapter => 2
	  		config.vm.hostname = 'Ansible.Master'
	  		vb.name = "Ansible-Master"
				vb.memory='2048'
		end
		#web.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		web.vm.provision "shell", path: "provision.sh"
		web.vm.provision "shell", path: "ansible.sh"
	end

	config.vm.define "Worker1" do |smanager|
		smanager.vm.box = "ubuntu/xenial64"
		smanager.vm.provider "virtualbox" do |vb|
	  		smanager.vm.network "private_network",ip:'192.168.56.7',:adapter => 2
	  		smanager.vm.hostname = 'worker1'
	  		vb.name = "Ansible-Worker1"
				vb.memory='1024'

		end
		#smanager.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		smanager.vm.provision "shell", path: "provision.sh"
	end

	config.vm.define "Worker2" do |worker|
		worker.vm.box = "ubuntu/xenial64"
		worker.vm.provider "virtualbox" do |vb|
	  		config.vm.network "private_network",ip:'192.168.56.8',:adapter => 2
	  		config.vm.hostname = 'Worker2'
	  		vb.name = "Ansible-Worker2"
				vb.memory='1024'

		end
		#worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		worker.vm.provision "shell", path: "provision.sh"
	end

	config.vm.define "Worker3" do |worker|
		worker.vm.box = "ubuntu/xenial64"
		worker.vm.provider "virtualbox" do |vb|
	  		config.vm.network "private_network",ip:'192.168.56.9',:adapter => 2
	  		config.vm.hostname = 'Worker3'
	  		vb.name = "Ansible-Worker3"
				vb.memory='1024'

		end
		#worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		worker.vm.provision "shell", path: "provision.sh"
	end


end
