
Vagrant.configure("2") do |config|

	config.vm.define "master" do |web|
		web.vm.box = "ubuntu/xenial64"
		web.vm.provider "virtualbox" do |vb|
	  		config.vm.network "private_network",ip:'192.168.56.10',:adapter => 2
	  		config.vm.hostname = 'master'
	  		vb.name = "master"
				vb.memory='2048'
		end
		#web.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		web.vm.provision "shell", path: "provision.sh"
		web.vm.provision "shell", path: "kubeadm.sh"
	end

	config.vm.define "worker1" do |smanager|
		smanager.vm.box = "ubuntu/xenial64"
		smanager.vm.provider "virtualbox" do |vb|
	  		smanager.vm.network "private_network",ip:'192.168.56.11',:adapter => 2
	  		smanager.vm.hostname = 'worker1'
	  		vb.name = "worker1"
				vb.memory='2048'

		end
		#smanager.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		smanager.vm.provision "shell", path: "provision.sh"
		smanager.vm.provision "shell", path: "kubeadm.sh"
	end

	config.vm.define "worker2" do |worker|
		worker.vm.box = "ubuntu/xenial64"
		worker.vm.provider "virtualbox" do |vb|
	  		config.vm.network "private_network",ip:'192.168.56.12',:adapter => 2
	  		config.vm.hostname = 'worker2'
	  		vb.name = "worker2"
				vb.memory='2048'

		end
		#worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
		worker.vm.provision "shell", path: "provision.sh"
		worker.vm.provision "shell", path: "kubeadm.sh"
	end



	config.push.define "atlas" do |push|
	  push.app = "abhijeetka/jenkins"
	  push.token = '4243wZsoj33Omw.atlasv1.8CqDvr2j0y6KSOr3ytVS78RL6xbYsekppf1t4oRUu2kNzG9cXkaIUtaRKMZcXlDegC4'
	end

end
